database:
    path: C:\Users\egors\Desktop\projectT\storage\projectT.db
    busy_timeout: 30000
    max_open_conns: 1
    max_idle_conns: 1
storage:
    path: C:\Users\egors\Desktop\projectT\storage
    files_dir: files
p2p:
    enabled: true
    port: 8079
    enable_relay: true
    enable_relay_discovery: true
prometheus:
    enabled: true
    port: 9090
    path: /metrics
    enable_p2p_metrics: true
